<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.security.frontend_user_provider' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\security\\Core\\User\\UserProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Security\\User\\ContaoUserProvider.php';

return $this->privates['contao.security.frontend_user_provider'] = new \Contao\CoreBundle\Security\User\ContaoUserProvider(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->services['session'] ?? $this->getSessionService()), 'Contao\\FrontendUser', ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
