<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.controller.backend_csv_import' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Controller\\BackendCsvImportController.php';

return $this->services['contao.controller.backend_csv_import'] = new \Contao\CoreBundle\Controller\BackendCsvImportController(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->services['translator'] ?? $this->getTranslatorService()), $this->targetDirs[3]);
