<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.installer' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\installation-bundle\\src\\Database\\Installer.php';

return $this->services['contao.installer'] = new \Contao\InstallationBundle\Database\Installer(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), ($this->privates['contao.doctrine.schema_provider'] ?? $this->load('getContao_Doctrine_SchemaProviderService.php')));
