<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.listener.header_replay.user_session' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\EventListener\\HeaderReplay\\UserSessionListener.php';

return $this->privates['contao.listener.header_replay.user_session'] = new \Contao\CoreBundle\EventListener\HeaderReplay\UserSessionListener(($this->services['contao.routing.scope_matcher'] ?? $this->getContao_Routing_ScopeMatcherService()), ($this->services['contao.security.token_checker'] ?? $this->getContao_Security_TokenCheckerService()));
