<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.image.picture_generator' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\image\\src\\PictureGeneratorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\image\\src\\PictureGenerator.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\image\\src\\ResizeCalculatorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\image\\src\\ResizeCalculator.php';

return $this->services['contao.image.picture_generator'] = new \Contao\Image\PictureGenerator(($this->services['contao.image.resizer'] ?? $this->load('getContao_Image_ResizerService.php')), ($this->privates['contao.image.resize_calculator'] ?? ($this->privates['contao.image.resize_calculator'] = new \Contao\Image\ResizeCalculator())));
