<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.install_tool' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\installation-bundle\\src\\InstallTool.php';

return $this->services['contao.install_tool'] = new \Contao\InstallationBundle\InstallTool(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), $this->targetDirs[3], ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
