<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.security.logout_handler' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\security\\Http\\Logout\\LogoutHandlerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Security\\Logout\\LogoutHandler.php';

return $this->privates['contao.security.logout_handler'] = new \Contao\CoreBundle\Security\Logout\LogoutHandler(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
