<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.fragment.renderer.forward' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Fragment\\FragmentRendererInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Fragment\\RoutableFragmentRenderer.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Fragment\\InlineFragmentRenderer.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Fragment\\ForwardFragmentRenderer.php';

$this->privates['contao.fragment.renderer.forward'] = $instance = new \Contao\CoreBundle\Fragment\ForwardFragmentRenderer(($this->services['http_kernel'] ?? $this->getHttpKernelService()), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));

$instance->setFragmentPath('/_fragment');

return $instance;
