<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.image.imagine' shared service.

include_once $this->targetDirs[3].'\\vendor\\imagine\\imagine\\src\\Factory\\ClassFactoryAwareInterface.php';
include_once $this->targetDirs[3].'\\vendor\\imagine\\imagine\\src\\Image\\ImagineInterface.php';
include_once $this->targetDirs[3].'\\vendor\\imagine\\imagine\\src\\Image\\AbstractImagine.php';
include_once $this->targetDirs[3].'\\vendor\\imagine\\imagine\\src\\Gd\\Imagine.php';

return $this->services['contao.image.imagine'] = new \Imagine\Gd\Imagine();
