<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.controller.insert_tags' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Controller\\InsertTagsController.php';

return $this->services['contao.controller.insert_tags'] = new \Contao\CoreBundle\Controller\InsertTagsController(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()));
