<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.security.two_factor.backend_provider' shared service.

include_once $this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\Provider\\TwoFactorProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Security\\TwoFactor\\Provider.php';
include_once $this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\Provider\\TwoFactorFormRendererInterface.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Security\\TwoFactor\\BackendFormRenderer.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Security\\TwoFactor\\Authenticator.php';

return $this->privates['contao.security.two_factor.backend_provider'] = new \Contao\CoreBundle\Security\TwoFactor\Provider(($this->services['contao.security.two_factor.authenticator'] ?? ($this->services['contao.security.two_factor.authenticator'] = new \Contao\CoreBundle\Security\TwoFactor\Authenticator())), new \Contao\CoreBundle\Security\TwoFactor\BackendFormRenderer(($this->services['router'] ?? $this->getRouterService())));
