<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.doctrine.schema_provider' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Doctrine\\Schema\\DcaSchemaProvider.php';

return $this->privates['contao.doctrine.schema_provider'] = new \Contao\CoreBundle\Doctrine\Schema\DcaSchemaProvider(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->services['doctrine'] ?? $this->getDoctrineService()));
