<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.listener.initialize_application' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\installation-bundle\\src\\EventListener\\InitializeApplicationListener.php';

$this->privates['contao.listener.initialize_application'] = $instance = new \Contao\InstallationBundle\EventListener\InitializeApplicationListener();

$instance->setContainer($this);

return $instance;
