<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.listener.data_container_callback' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\EventListener\\DataContainerCallbackListener.php';

return $this->services['contao.listener.data_container_callback'] = new \Contao\CoreBundle\EventListener\DataContainerCallbackListener();
