<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.listener.GgExw63' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\EventListener\\GlobalsMapListener.php';

return $this->services['contao.listener.GgExw63'] = new \Contao\CoreBundle\EventListener\GlobalsMapListener([]);
