<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.image.picture_factory' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Image\\PictureFactoryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Image\\PictureFactory.php';

return $this->services['contao.image.picture_factory'] = new \Contao\CoreBundle\Image\PictureFactory(($this->services['contao.image.picture_generator'] ?? $this->load('getContao_Image_PictureGeneratorService.php')), ($this->services['contao.image.image_factory'] ?? $this->load('getContao_Image_ImageFactoryService.php')), ($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), false, $this->parameters['contao.image.imagine_options']);
