<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fragment.renderer.hinclude' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Fragment\\FragmentRendererInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Fragment\\RoutableFragmentRenderer.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Fragment\\HIncludeFragmentRenderer.php';

$this->privates['fragment.renderer.hinclude'] = $instance = new \Symfony\Component\HttpKernel\Fragment\HIncludeFragmentRenderer(($this->services['twig'] ?? $this->load('getTwigService.php')), ($this->privates['uri_signer'] ?? ($this->privates['uri_signer'] = new \Symfony\Component\HttpKernel\UriSigner('2c68ae793b72808e441efe92c1bf2d934981357c725c665bd1e94d2501b27a03'))), NULL);

$instance->setFragmentPath('/_fragment');

return $instance;
