<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'scheb_two_factor.ip_whitelist_handler' shared service.

include_once $this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\Handler\\AuthenticationHandlerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\Handler\\IpWhitelistHandler.php';
include_once $this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\IpWhitelist\\IpWhitelistProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\IpWhitelist\\DefaultIpWhitelistProvider.php';

if ($lazyLoad) {
    return $this->privates['scheb_two_factor.ip_whitelist_handler'] = $this->createProxy('IpWhitelistHandler_06fe2b0', function () {
        return \IpWhitelistHandler_06fe2b0::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getSchebTwoFactor_IpWhitelistHandlerService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \Scheb\TwoFactorBundle\Security\TwoFactor\Handler\IpWhitelistHandler(($this->privates['scheb_two_factor.trusted_device_handler'] ?? $this->load('getSchebTwoFactor_TrustedDeviceHandlerService.php')), new \Scheb\TwoFactorBundle\Security\TwoFactor\IpWhitelist\DefaultIpWhitelistProvider([]));
