<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.rememberme.contao_frontend.two_factor_decorator' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\security\\Core\\Authentication\\AuthenticationManagerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security\\Core\\Authentication\\Provider\\AuthenticationProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle\\Security\\Authentication\\Provider\\AuthenticationProviderDecorator.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security\\Core\\Authentication\\Provider\\RememberMeAuthenticationProvider.php';
include_once $this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\AuthenticationContextFactoryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\AuthenticationContextFactory.php';

return $this->privates['security.authentication.provider.rememberme.contao_frontend.two_factor_decorator'] = new \Scheb\TwoFactorBundle\Security\Authentication\Provider\AuthenticationProviderDecorator(new \Symfony\Component\Security\Core\Authentication\Provider\RememberMeAuthenticationProvider(($this->privates['contao.security.user_checker'] ?? $this->load('getContao_Security_UserCheckerService.php')), '2c68ae793b72808e441efe92c1bf2d934981357c725c665bd1e94d2501b27a03', 'contao_frontend'), ($this->privates['scheb_two_factor.authenticated_token_handler'] ?? $this->load('getSchebTwoFactor_AuthenticatedTokenHandlerService.php')), ($this->privates['scheb_two_factor.authentication_context_factory'] ?? ($this->privates['scheb_two_factor.authentication_context_factory'] = new \Scheb\TwoFactorBundle\Security\TwoFactor\AuthenticationContextFactory('Scheb\\TwoFactorBundle\\Security\\TwoFactor\\AuthenticationContext'))), ($this->services['security.firewall.map'] ?? $this->getSecurity_Firewall_MapService()), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
