<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'twig' shared service.

include_once $this->targetDirs[3].'\\vendor\\twig\\twig\\src\\Environment.php';
include_once $this->targetDirs[3].'\\vendor\\twig\\twig\\src\\Loader\\LoaderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\twig\\twig\\src\\Loader\\ExistsLoaderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\twig\\twig\\src\\Loader\\SourceContextLoaderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\twig\\twig\\src\\Loader\\FilesystemLoader.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\twig-bundle\\Loader\\FilesystemLoader.php';
include_once $this->targetDirs[3].'\\vendor\\twig\\twig\\src\\Extension\\ExtensionInterface.php';
include_once $this->targetDirs[3].'\\vendor\\twig\\twig\\src\\Extension\\AbstractExtension.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\twig-bridge\\Extension\\CsrfExtension.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\twig-bridge\\Extension\\LogoutUrlExtension.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\twig-bridge\\Extension\\SecurityExtension.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\twig-bridge\\Extension\\TranslationExtension.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\twig-bridge\\Extension\\AssetExtension.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\twig-bridge\\Extension\\CodeExtension.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\twig-bridge\\Extension\\RoutingExtension.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\twig-bridge\\Extension\\YamlExtension.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\twig-bridge\\Extension\\ExpressionExtension.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\twig-bridge\\Extension\\HttpKernelExtension.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\twig-bridge\\Extension\\HttpFoundationExtension.php';
include_once $this->targetDirs[3].'\\vendor\\knplabs\\knp-menu\\src\\Knp\\Menu\\Twig\\MenuExtension.php';
include_once $this->targetDirs[3].'\\vendor\\knplabs\\knp-menu\\src\\Knp\\Menu\\Twig\\Helper.php';
include_once $this->targetDirs[3].'\\vendor\\knplabs\\knp-menu\\src\\Knp\\Menu\\Renderer\\RendererProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\knplabs\\knp-menu\\src\\Knp\\Menu\\Renderer\\PsrProvider.php';
include_once $this->targetDirs[3].'\\vendor\\knplabs\\knp-menu\\src\\Knp\\Menu\\Provider\\MenuProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\knplabs\\knp-menu\\src\\Knp\\Menu\\Provider\\ChainProvider.php';
include_once $this->targetDirs[3].'\\vendor\\knplabs\\knp-menu\\src\\Knp\\Menu\\Util\\MenuManipulator.php';
include_once $this->targetDirs[3].'\\vendor\\knplabs\\knp-time-bundle\\Knp\\Bundle\\TimeBundle\\Twig\\Extension\\TimeExtension.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\templating\\Helper\\HelperInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\templating\\Helper\\Helper.php';
include_once $this->targetDirs[3].'\\vendor\\knplabs\\knp-time-bundle\\Knp\\Bundle\\TimeBundle\\Templating\\Helper\\TimeHelper.php';
include_once $this->targetDirs[3].'\\vendor\\knplabs\\knp-time-bundle\\Knp\\Bundle\\TimeBundle\\DateTimeFormatter.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\doctrine-bundle\\Twig\\DoctrineExtension.php';
include_once $this->targetDirs[3].'\\vendor\\nelmio\\security-bundle\\Twig\\NelmioCSPTwigExtension.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\http-cache-bundle\\src\\Twig\\CacheTagExtension.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Twig\\Extension\\ContaoTemplateExtension.php';
include_once $this->targetDirs[3].'\\vendor\\sensiolabs\\ansi-to-html\\SensioLabs\\AnsiConverter\\Bridge\\Twig\\AnsiExtension.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\twig-bridge\\AppVariable.php';
include_once $this->targetDirs[3].'\\vendor\\twig\\twig\\src\\RuntimeLoader\\RuntimeLoaderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\twig\\twig\\src\\RuntimeLoader\\ContainerRuntimeLoader.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\twig-bundle\\DependencyInjection\\Configurator\\EnvironmentConfigurator.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\templating\\TemplateNameParserInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\templating\\TemplateNameParser.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Templating\\TemplateNameParser.php';

$a = new \Symfony\Bundle\TwigBundle\Loader\FilesystemLoader(($this->privates['templating.locator'] ?? $this->load('getTemplating_LocatorService.php')), ($this->privates['templating.name_parser'] ?? ($this->privates['templating.name_parser'] = new \Symfony\Bundle\FrameworkBundle\Templating\TemplateNameParser(($this->services['kernel'] ?? $this->get('kernel', 1))))), $this->targetDirs[3]);
$a->addPath(($this->targetDirs[3].'\\vendor\\knplabs\\knp-menu\\src\\Knp\\Menu/Resources/views'));
$a->addPath(($this->targetDirs[3].'\\vendor\\knplabs\\knp-menu-bundle\\src/Resources/views'), 'KnpMenu');
$a->addPath(($this->targetDirs[3].'\\vendor\\knplabs\\knp-menu-bundle\\src/Resources/views'), '!KnpMenu');
$a->addPath(($this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle/Resources/views'), 'SchebTwoFactor');
$a->addPath(($this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle/Resources/views'), '!SchebTwoFactor');
$a->addPath(($this->targetDirs[3].'\\vendor\\symfony\\framework-bundle/Resources/views'), 'Framework');
$a->addPath(($this->targetDirs[3].'\\vendor\\symfony\\framework-bundle/Resources/views'), '!Framework');
$a->addPath(($this->targetDirs[3].'\\vendor\\symfony\\security-bundle/Resources/views'), 'Security');
$a->addPath(($this->targetDirs[3].'\\vendor\\symfony\\security-bundle/Resources/views'), '!Security');
$a->addPath(($this->targetDirs[3].'\\vendor\\symfony\\twig-bundle/Resources/views'), 'Twig');
$a->addPath(($this->targetDirs[3].'\\vendor\\symfony\\twig-bundle/Resources/views'), '!Twig');
$a->addPath(($this->targetDirs[3].'\\vendor\\symfony\\swiftmailer-bundle/Resources/views'), 'Swiftmailer');
$a->addPath(($this->targetDirs[3].'\\vendor\\symfony\\swiftmailer-bundle/Resources/views'), '!Swiftmailer');
$a->addPath(($this->targetDirs[3].'\\vendor\\doctrine\\doctrine-bundle/Resources/views'), 'Doctrine');
$a->addPath(($this->targetDirs[3].'\\vendor\\doctrine\\doctrine-bundle/Resources/views'), '!Doctrine');
$a->addPath(($this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src/Resources/views'), 'ContaoCore');
$a->addPath(($this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src/Resources/views'), '!ContaoCore');
$a->addPath(($this->targetDirs[3].'\\vendor\\contao\\installation-bundle\\src/Resources/views'), 'ContaoInstallation');
$a->addPath(($this->targetDirs[3].'\\vendor\\contao\\installation-bundle\\src/Resources/views'), '!ContaoInstallation');

$this->services['twig'] = $instance = new \Twig\Environment($a, ['paths' => [($this->targetDirs[3].'\\vendor\\knplabs\\knp-menu\\src\\Knp\\Menu/Resources/views') => NULL], 'debug' => false, 'strict_variables' => false, 'default_path' => ($this->targetDirs[3].'/app/Resources/views'), 'exception_controller' => 'twig.controller.exception::showAction', 'form_themes' => $this->parameters['twig.form.resources'], 'autoescape' => 'name', 'cache' => ($this->targetDirs[0].'/twig'), 'charset' => 'UTF-8', 'date' => ['format' => 'F j, Y H:i', 'interval_format' => '%d days', 'timezone' => NULL], 'number_format' => ['decimals' => 0, 'decimal_point' => '.', 'thousands_separator' => ',']]);

$b = ($this->services['translator'] ?? $this->getTranslatorService());
$c = ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));
$d = new \Knp\Menu\Util\MenuManipulator();
$e = ($this->services['knp_menu.matcher'] ?? $this->load('getKnpMenu_MatcherService.php'));
$f = new \Symfony\Bridge\Twig\AppVariable();
$f->setEnvironment('prod');
$f->setDebug(false);
if ($this->has('security.token_storage')) {
    $f->setTokenStorage(($this->services['security.token_storage'] ?? ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())));
}
if ($this->has('request_stack')) {
    $f->setRequestStack($c);
}

$instance->addExtension(new \Symfony\Bridge\Twig\Extension\CsrfExtension());
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\LogoutUrlExtension(($this->services['security.logout_url_generator'] ?? $this->getSecurity_LogoutUrlGeneratorService())));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\SecurityExtension(($this->services['security.authorization_checker'] ?? $this->load('getSecurity_AuthorizationCheckerService.php'))));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\TranslationExtension($b));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\AssetExtension(($this->services['assets.packages'] ?? $this->load('getAssets_PackagesService.php'))));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\CodeExtension(($this->privates['debug.file_link_formatter'] ?? ($this->privates['debug.file_link_formatter'] = new \Symfony\Component\HttpKernel\Debug\FileLinkFormatter(NULL))), $this->targetDirs[3], 'UTF-8'));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\RoutingExtension(($this->services['router'] ?? $this->getRouterService())));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\YamlExtension());
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\ExpressionExtension());
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\HttpKernelExtension());
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\HttpFoundationExtension($c, ($this->privates['router.request_context'] ?? $this->getRouter_RequestContextService())));
$instance->addExtension(new \Knp\Menu\Twig\MenuExtension(new \Knp\Menu\Twig\Helper(new \Knp\Menu\Renderer\PsrProvider(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'list' => ['privates', 'knp_menu.renderer.list', 'getKnpMenu_Renderer_ListService.php', true],
    'twig' => ['privates', 'knp_menu.renderer.twig', 'getKnpMenu_Renderer_TwigService.php', true],
]), 'twig'), new \Knp\Menu\Provider\ChainProvider(new RewindableGenerator(function () {
    yield 0 => ($this->privates['knp_menu.menu_provider.lazy'] ?? ($this->privates['knp_menu.menu_provider.lazy'] = new \Knp\Menu\Provider\LazyProvider([])));
    yield 1 => ($this->privates['knp_menu.menu_provider.builder_alias'] ?? $this->load('getKnpMenu_MenuProvider_BuilderAliasService.php'));
}, 2)), $d, $e), $e, $d));
$instance->addExtension(new \Knp\Bundle\TimeBundle\Twig\Extension\TimeExtension(new \Knp\Bundle\TimeBundle\Templating\Helper\TimeHelper(new \Knp\Bundle\TimeBundle\DateTimeFormatter($b))));
$instance->addExtension(new \Doctrine\Bundle\DoctrineBundle\Twig\DoctrineExtension());
$instance->addExtension(new \Nelmio\SecurityBundle\Twig\NelmioCSPTwigExtension(($this->privates['nelmio_security.csp_listener'] ?? $this->getNelmioSecurity_CspListenerService()), ($this->privates['nelmio_security.sha_computer'] ?? ($this->privates['nelmio_security.sha_computer'] = new \Nelmio\SecurityBundle\ContentSecurityPolicy\ShaComputer('sha256')))));
$instance->addExtension(new \FOS\HttpCacheBundle\Twig\CacheTagExtension(($this->services['fos_http_cache.http.symfony_response_tagger'] ?? $this->getFosHttpCache_Http_SymfonyResponseTaggerService())));
$instance->addExtension(new \Contao\CoreBundle\Twig\Extension\ContaoTemplateExtension($c, ($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->services['contao.routing.scope_matcher'] ?? $this->getContao_Routing_ScopeMatcherService())));
$instance->addExtension(new \SensioLabs\AnsiConverter\Bridge\Twig\AnsiExtension());
$instance->addGlobal('app', $f);
$instance->addRuntimeLoader(new \Twig\RuntimeLoader\ContainerRuntimeLoader(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Symfony\\Bridge\\Twig\\Extension\\CsrfRuntime' => ['privates', 'twig.runtime.security_csrf', 'getTwig_Runtime_SecurityCsrfService.php', true],
    'Symfony\\Bridge\\Twig\\Extension\\HttpKernelRuntime' => ['privates', 'twig.runtime.httpkernel', 'getTwig_Runtime_HttpkernelService.php', true],
])));
(new \Symfony\Bundle\TwigBundle\DependencyInjection\Configurator\EnvironmentConfigurator('F j, Y H:i', '%d days', NULL, 0, '.', ','))->configure($instance);

return $instance;
