<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'DoctrineNamespaceCacheKey%5B%5D' => 0,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23setContainer%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getParameter%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getSubscribedServices%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23has%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23get%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23generateUrl%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23forward%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23redirect%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23redirectToRoute%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23json%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23file%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23addFlash%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23isGranted%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23denyAccessUnlessGranted%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23renderView%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23render%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23stream%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createNotFoundException%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createAccessDeniedException%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createForm%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createFormBuilder%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getDoctrine%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getUser%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23isCsrfTokenValid%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23dispatchMessage%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23addLink%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%24container%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CAbstractFragmentController%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CAbstractFragmentController%23setFragmentOptions%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CAbstractFragmentController%23getSubscribedServices%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CAbstractFragmentController%23createTemplate%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CAbstractFragmentController%23addHeadlineToTemplate%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CAbstractFragmentController%23addCssAttributesToTemplate%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CAbstractFragmentController%23addSectionToTemplate%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CAbstractFragmentController%23tagResponse%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CAbstractFragmentController%23getType%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CAbstractFragmentController%24options%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendController%5D%5B1%5D' => 2,
'%5BContao%5CCoreBundle%5CController%5CBackendController%23mainAction%5D%5B1%5D' => 3,
'%5BContao%5CCoreBundle%5CController%5CBackendController%23loginAction%5D%5B1%5D' => 4,
'%5BContao%5CCoreBundle%5CController%5CBackendController%23logoutAction%5D%5B1%5D' => 5,
'%5BContao%5CCoreBundle%5CController%5CBackendController%23passwordAction%5D%5B1%5D' => 6,
'%5BContao%5CCoreBundle%5CController%5CBackendController%23previewAction%5D%5B1%5D' => 7,
'%5BContao%5CCoreBundle%5CController%5CBackendController%23confirmAction%5D%5B1%5D' => 8,
'%5BContao%5CCoreBundle%5CController%5CBackendController%23fileAction%5D%5B1%5D' => 9,
'%5BContao%5CCoreBundle%5CController%5CBackendController%23helpAction%5D%5B1%5D' => 10,
'%5BContao%5CCoreBundle%5CController%5CBackendController%23pageAction%5D%5B1%5D' => 11,
'%5BContao%5CCoreBundle%5CController%5CBackendController%23popupAction%5D%5B1%5D' => 12,
'%5BContao%5CCoreBundle%5CController%5CBackendController%23switchAction%5D%5B1%5D' => 13,
'%5BContao%5CCoreBundle%5CController%5CBackendController%23alertsAction%5D%5B1%5D' => 14,
'%5BContao%5CCoreBundle%5CController%5CBackendController%23pickerAction%5D%5B1%5D' => 15,
'%5BContao%5CCoreBundle%5CController%5CBackendController%23twoFactorAuthenticationAction%5D%5B1%5D' => 16,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%23__construct%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%23importListWizardAction%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%23importTableWizardAction%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%23importOptionWizardAction%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%23importFromTemplate%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%23prepareTemplate%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%23fetchData%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%23getFormId%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%23getBackUrl%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%23getSeparators%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%23getDelimiter%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%23getFiles%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%24framework%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%24connection%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%24requestStack%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%24translator%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CBackendCsvImportController%24projectDir%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CContentElement%5CAbstractContentElementController%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CContentElement%5CAbstractContentElementController%23__invoke%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CContentElement%5CAbstractContentElementController%23addSharedMaxAgeToResponse%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CContentElement%5CAbstractContentElementController%23getResponse%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CFrontendController%5D%5B1%5D' => 17,
'%5BContao%5CCoreBundle%5CController%5CFrontendController%23indexAction%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CFrontendController%23cronAction%5D%5B1%5D' => 18,
'%5BContao%5CCoreBundle%5CController%5CFrontendController%23shareAction%5D%5B1%5D' => 19,
'%5BContao%5CCoreBundle%5CController%5CFrontendController%23loginAction%5D%5B1%5D' => 20,
'%5BContao%5CCoreBundle%5CController%5CFrontendController%23logoutAction%5D%5B1%5D' => 21,
'%5BContao%5CCoreBundle%5CController%5CFrontendModule%5CAbstractFrontendModuleController%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CFrontendModule%5CAbstractFrontendModuleController%23__invoke%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CFrontendModule%5CAbstractFrontendModuleController%23getSubscribedServices%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CFrontendModule%5CAbstractFrontendModuleController%23getBackendWildcard%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CFrontendModule%5CAbstractFrontendModuleController%23getResponse%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CInitializeController%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CInitializeController%23indexAction%5D%5B1%5D' => 22,
'%5BContao%5CCoreBundle%5CController%5CInsertTagsController%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CInsertTagsController%23__construct%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CInsertTagsController%23renderAction%5D%5B1%5D' => 1,
'%5BContao%5CCoreBundle%5CController%5CInsertTagsController%24framework%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%5D%5B1%5D' => 23,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23installAction%5D%5B1%5D' => 24,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23initializeApplication%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23acceptLicense%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23setPassword%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23login%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23purgeSymfonyCache%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23warmUpSymfonyCache%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23setUpDatabaseConnection%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23runDatabaseUpdates%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23adjustDatabaseTables%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23importExampleWebsite%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23createAdminUser%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23render%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23trans%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23getRedirectResponse%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23addDefaultsToContext%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23getRequestToken%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23getContainerParameter%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23getUserAgentString%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%23setContainer%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%24context%5D%5B1%5D' => 1,
'%5BContao%5CInstallationBundle%5CController%5CInstallationController%24container%5D%5B1%5D' => 1,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%5D%5B1%5D' => 1,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23setContainer%5D%5B1%5D' => 1,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainAction%5D%5B1%5D' => 1,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainSQLServerPlatform%5D%5B1%5D' => 1,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainOtherPlatform%5D%5B1%5D' => 1,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%24container%5D%5B1%5D' => 1,
'%5BNelmio%5CSecurityBundle%5CController%5CContentSecurityPolicyController%5D%5B1%5D' => 1,
'%5BNelmio%5CSecurityBundle%5CController%5CContentSecurityPolicyController%23__construct%5D%5B1%5D' => 1,
'%5BNelmio%5CSecurityBundle%5CController%5CContentSecurityPolicyController%23indexAction%5D%5B1%5D' => 1,
'%5BNelmio%5CSecurityBundle%5CController%5CContentSecurityPolicyController%24logger%5D%5B1%5D' => 1,
'%5BNelmio%5CSecurityBundle%5CController%5CContentSecurityPolicyController%24filter%5D%5B1%5D' => 1,
'%5BNelmio%5CSecurityBundle%5CController%5CContentSecurityPolicyController%24dispatcher%5D%5B1%5D' => 1,
'%5BScheb%5CTwoFactorBundle%5CController%5CFormController%5D%5B1%5D' => 1,
'%5BScheb%5CTwoFactorBundle%5CController%5CFormController%23__construct%5D%5B1%5D' => 1,
'%5BScheb%5CTwoFactorBundle%5CController%5CFormController%23form%5D%5B1%5D' => 1,
'%5BScheb%5CTwoFactorBundle%5CController%5CFormController%23getTwoFactorToken%5D%5B1%5D' => 1,
'%5BScheb%5CTwoFactorBundle%5CController%5CFormController%23setPreferredProvider%5D%5B1%5D' => 1,
'%5BScheb%5CTwoFactorBundle%5CController%5CFormController%23getTemplateVars%5D%5B1%5D' => 1,
'%5BScheb%5CTwoFactorBundle%5CController%5CFormController%23getLastAuthenticationException%5D%5B1%5D' => 1,
'%5BScheb%5CTwoFactorBundle%5CController%5CFormController%24tokenStorage%5D%5B1%5D' => 1,
'%5BScheb%5CTwoFactorBundle%5CController%5CFormController%24providerRegistry%5D%5B1%5D' => 1,
'%5BScheb%5CTwoFactorBundle%5CController%5CFormController%24twoFactorFirewallContext%5D%5B1%5D' => 1,
'%5BScheb%5CTwoFactorBundle%5CController%5CFormController%24trustedFeatureEnabled%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23getParameter%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23setContainer%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23has%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23get%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23generateUrl%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23forward%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23redirect%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23redirectToRoute%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23json%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23file%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23addFlash%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23isGranted%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23denyAccessUnlessGranted%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23renderView%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23render%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23stream%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23createNotFoundException%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23createAccessDeniedException%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23createForm%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23createFormBuilder%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23getDoctrine%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23getUser%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23isCsrfTokenValid%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23dispatchMessage%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%23addLink%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CController%24container%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23__construct%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23getAndCleanOutputBuffering%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23findTemplate%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%23templateExists%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%24twig%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CTwigBundle%5CController%5CExceptionController%24debug%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CTwigBundle%5CController%5CPreviewErrorController%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CTwigBundle%5CController%5CPreviewErrorController%23__construct%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CTwigBundle%5CController%5CPreviewErrorController%23previewErrorPageAction%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CTwigBundle%5CController%5CPreviewErrorController%24kernel%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CTwigBundle%5CController%5CPreviewErrorController%24controller%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CExceptionController%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CExceptionController%23__construct%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CExceptionController%23showAction%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CExceptionController%23cssAction%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CExceptionController%23getTemplate%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CExceptionController%23templateExists%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CExceptionController%24twig%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CExceptionController%24debug%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CExceptionController%24profiler%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CExceptionController%24fileLinkFormat%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23__construct%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23homeAction%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23panelAction%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23toolbarAction%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23searchBarAction%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23searchResultsAction%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23searchAction%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23phpinfoAction%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23openAction%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23getTemplateManager%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%23renderWithCspNonces%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%24templateManager%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%24generator%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%24profiler%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%24twig%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%24templates%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%24cspHandler%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CProfilerController%24baseDir%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController%23__construct%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController%23panelAction%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController%23getTraces%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController%24profiler%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController%24twig%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController%24matcher%5D%5B1%5D' => 1,
'%5BSymfony%5CBundle%5CWebProfilerBundle%5CController%5CRouterController%24routes%5D%5B1%5D' => 1,
'%5BSymfony%5CCmf%5CBundle%5CRoutingBundle%5CController%5CRedirectController%5D%5B1%5D' => 1,
'%5BSymfony%5CCmf%5CBundle%5CRoutingBundle%5CController%5CRedirectController%23__construct%5D%5B1%5D' => 1,
'%5BSymfony%5CCmf%5CBundle%5CRoutingBundle%5CController%5CRedirectController%23redirectAction%5D%5B1%5D' => 1,
'%5BSymfony%5CCmf%5CBundle%5CRoutingBundle%5CController%5CRedirectController%24router%5D%5B1%5D' => 1,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%5D%5B1%5D' => 1,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23__construct%5D%5B1%5D' => 1,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23supports%5D%5B1%5D' => 1,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23resolve%5D%5B1%5D' => 1,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%24tokenStorage%5D%5B1%5D' => 1,

], [

0 => 'N;',
1 => [],
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'defaults' => [
                    [
                        '_scope' => 'backend',
                        '_token_check' => true,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/contao',
                ],
                'name' => [
                    'contao_backend',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/contao/login',
                ],
                'name' => [
                    'contao_backend_login',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/contao/logout',
                ],
                'name' => [
                    'contao_backend_logout',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/contao/password',
                ],
                'name' => [
                    'contao_backend_password',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/contao/preview',
                ],
                'name' => [
                    'contao_backend_preview',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/contao/confirm',
                ],
                'name' => [
                    'contao_backend_confirm',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
9 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/contao/file',
                ],
                'name' => [
                    'contao_backend_file',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
10 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/contao/help',
                ],
                'name' => [
                    'contao_backend_help',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
11 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/contao/page',
                ],
                'name' => [
                    'contao_backend_page',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
12 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/contao/popup',
                ],
                'name' => [
                    'contao_backend_popup',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
13 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/contao/switch',
                ],
                'name' => [
                    'contao_backend_switch',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
14 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/contao/alerts',
                ],
                'name' => [
                    'contao_backend_alerts',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
15 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/contao/picker',
                ],
                'name' => [
                    'contao_backend_picker',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
16 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/contao/two-factor',
                ],
                'name' => [
                    'contao_backend_two_factor',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
17 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'defaults' => [
                    [
                        '_scope' => 'frontend',
                        '_token_check' => true,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
18 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/_contao/cron',
                ],
                'name' => [
                    'contao_frontend_cron',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
19 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/_contao/share',
                ],
                'name' => [
                    'contao_frontend_share',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
20 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/_contao/login',
                ],
                'name' => [
                    'contao_frontend_login',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
21 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/_contao/logout',
                ],
                'name' => [
                    'contao_frontend_logout',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
22 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/_contao/initialize',
                ],
                'name' => [
                    'contao_initialize',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
23 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/contao',
                ],
                'defaults' => [
                    [
                        '_scope' => 'backend',
                        '_token_check' => true,
                    ],
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
24 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Routing\\Annotation\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Routing\\Annotation\\Route')),
        ],
        null,
        [
            'Symfony\\Component\\Routing\\Annotation\\Route' => [
                'path' => [
                    '/install',
                ],
                'name' => [
                    'contao_install',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},

]];
