<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU4ukGDj\appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU4ukGDj/appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer.php') {
    touch(__DIR__.'/ContainerU4ukGDj.legacy');

    return;
}

if (!\class_exists(appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false)) {
    \class_alias(\ContainerU4ukGDj\appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false);
}

return new \ContainerU4ukGDj\appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer([
    'container.build_hash' => 'U4ukGDj',
    'container.build_id' => '110c90bc',
    'container.build_time' => 1559124062,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU4ukGDj');
