<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'assets.packages' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\asset\\Packages.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\asset\\PackageInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\asset\\Package.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\asset\\PathPackage.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\asset\\VersionStrategy\\VersionStrategyInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\asset\\VersionStrategy\\EmptyVersionStrategy.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\asset\\Context\\ContextInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\asset\\Context\\RequestStackContext.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\asset\\VersionStrategy\\StaticVersionStrategy.php';

$a = new \Symfony\Component\Asset\VersionStrategy\EmptyVersionStrategy();

$this->services['assets.packages'] = $instance = new \Symfony\Component\Asset\Packages(new \Symfony\Component\Asset\PathPackage('', $a, new \Symfony\Component\Asset\Context\RequestStackContext(($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), '', false)), []);

$b = ($this->services['contao.assets.assets_context'] ?? $this->load('getContao_Assets_AssetsContextService.php'));

$instance->addPackage('contao_core', new \Symfony\Component\Asset\PathPackage('bundles/contaocore', $a, $b));
$instance->addPackage('contao_calendar', new \Symfony\Component\Asset\PathPackage('bundles/contaocalendar', $a, $b));
$instance->addPackage('contao_comments', new \Symfony\Component\Asset\PathPackage('bundles/contaocomments', $a, $b));
$instance->addPackage('contao_faq', new \Symfony\Component\Asset\PathPackage('bundles/contaofaq', $a, $b));
$instance->addPackage('contao_news', new \Symfony\Component\Asset\PathPackage('bundles/contaonews', $a, $b));
$instance->addPackage('contao_newsletter', new \Symfony\Component\Asset\PathPackage('bundles/contaonewsletter', $a, $b));
$instance->addPackage('contao-components/ace', new \Symfony\Component\Asset\PathPackage('assets/ace', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('1.4.4', '%s?v=%s'), $b));
$instance->addPackage('contao-components/chosen', new \Symfony\Component\Asset\PathPackage('assets/chosen', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('1.2.1', '%s?v=%s'), $b));
$instance->addPackage('contao-components/colorbox', new \Symfony\Component\Asset\PathPackage('assets/colorbox', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('1.6.4.1', '%s?v=%s'), $b));
$instance->addPackage('contao-components/colorpicker', new \Symfony\Component\Asset\PathPackage('assets/colorpicker', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('1.5.0', '%s?v=%s'), $b));
$instance->addPackage('contao-components/compass', new \Symfony\Component\Asset\PathPackage('assets/compass', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('0.12.2.1', '%s?v=%s'), $b));
$instance->addPackage('contao-components/contao', new \Symfony\Component\Asset\PathPackage('assets/contao', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('8.0.3', '%s?v=%s'), $b));
$instance->addPackage('contao-components/datepicker', new \Symfony\Component\Asset\PathPackage('assets/datepicker', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('2.3.0', '%s?v=%s'), $b));
$instance->addPackage('contao-components/dropzone', new \Symfony\Component\Asset\PathPackage('assets/dropzone', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('5.5.0', '%s?v=%s'), $b));
$instance->addPackage('contao-components/highlight', new \Symfony\Component\Asset\PathPackage('assets/highlight', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('9.15.6', '%s?v=%s'), $b));
$instance->addPackage('contao-components/html5shiv', new \Symfony\Component\Asset\PathPackage('assets/html5shiv', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('3.7.3', '%s?v=%s'), $b));
$instance->addPackage('contao-components/installer', new \Symfony\Component\Asset\PathPackage('assets/installer', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('1.3.1', '%s?v=%s'), $b));
$instance->addPackage('contao-components/jquery', new \Symfony\Component\Asset\PathPackage('assets/jquery', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('3.4.1', '%s?v=%s'), $b));
$instance->addPackage('contao-components/jquery-ui', new \Symfony\Component\Asset\PathPackage('assets/jquery-ui', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('1.12.1.1', '%s?v=%s'), $b));
$instance->addPackage('contao-components/mediabox', new \Symfony\Component\Asset\PathPackage('assets/mediabox', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('1.5.4.2', '%s?v=%s'), $b));
$instance->addPackage('contao-components/mediaelement', new \Symfony\Component\Asset\PathPackage('assets/mediaelement', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('4.2.10', '%s?v=%s'), $b));
$instance->addPackage('contao-components/mootools', new \Symfony\Component\Asset\PathPackage('assets/mootools', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('1.6.0.5', '%s?v=%s'), $b));
$instance->addPackage('contao-components/respimage', new \Symfony\Component\Asset\PathPackage('assets/respimage', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('1.4.2', '%s?v=%s'), $b));
$instance->addPackage('contao-components/simplemodal', new \Symfony\Component\Asset\PathPackage('assets/simplemodal', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('2.1.0', '%s?v=%s'), $b));
$instance->addPackage('contao-components/swipe', new \Symfony\Component\Asset\PathPackage('assets/swipe', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('2.1.2', '%s?v=%s'), $b));
$instance->addPackage('contao-components/tablesort', new \Symfony\Component\Asset\PathPackage('assets/tablesort', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('3.4.11', '%s?v=%s'), $b));
$instance->addPackage('contao-components/tablesorter', new \Symfony\Component\Asset\PathPackage('assets/tablesorter', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('2.1.0', '%s?v=%s'), $b));
$instance->addPackage('contao-components/tinymce4', new \Symfony\Component\Asset\PathPackage('assets/tinymce4', new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('4.9.4', '%s?v=%s'), $b));

return $instance;
