<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.listener.header_replay.page_layout' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\EventListener\\HeaderReplay\\PageLayoutListener.php';

return $this->privates['contao.listener.header_replay.page_layout'] = new \Contao\CoreBundle\EventListener\HeaderReplay\PageLayoutListener(($this->services['contao.routing.scope_matcher'] ?? $this->getContao_Routing_ScopeMatcherService()), ($this->services['contao.framework'] ?? $this->getContao_FrameworkService()));
