<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.contao.command.filesync' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\console\\Command\\Command.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Framework\\FrameworkAwareInterface.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Framework\\FrameworkAwareTrait.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Command\\FilesyncCommand.php';

$this->services['console.command.public_alias.contao.command.filesync'] = $instance = new \Contao\CoreBundle\Command\FilesyncCommand();

$instance->setFramework(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()));

return $instance;
