<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.contao.command.automator' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\console\\Command\\Command.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Command\\AutomatorCommand.php';

return $this->services['console.command.public_alias.contao.command.automator'] = new \Contao\CoreBundle\Command\AutomatorCommand(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()));
