<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.command.symlinks' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\console\\Command\\Command.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Command\\SymlinksCommand.php';

return $this->services['contao.command.symlinks'] = new \Contao\CoreBundle\Command\SymlinksCommand($this->targetDirs[3], 'files', ($this->targetDirs[2].'\\logs'), ($this->services['contao.resource_finder'] ?? $this->load('getContao_ResourceFinderService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
