<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.listener.insert_tags.translation' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\EventListener\\InsertTags\\TranslationListener.php';

return $this->services['contao.listener.insert_tags.translation'] = new \Contao\CoreBundle\EventListener\InsertTags\TranslationListener(($this->services['translator'] ?? $this->getTranslatorService()));
