<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.menu.backend_menu_builder' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Menu\\BackendMenuBuilder.php';

return $this->services['contao.menu.backend_menu_builder'] = new \Contao\CoreBundle\Menu\BackendMenuBuilder(($this->services['knp_menu.factory'] ?? $this->load('getKnpMenu_FactoryService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
