<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.security.frontend_preview_authenticator' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Security\\Authentication\\FrontendPreviewAuthenticator.php';

return $this->services['contao.security.frontend_preview_authenticator'] = new \Contao\CoreBundle\Security\Authentication\FrontendPreviewAuthenticator(($this->services['session'] ?? $this->getSessionService()), ($this->services['security.token_storage'] ?? ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())), ($this->privates['contao.security.frontend_user_provider'] ?? $this->load('getContao_Security_FrontendUserProviderService.php')), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
