<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.picker.builder' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Picker\\PickerBuilderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Picker\\PickerBuilder.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Picker\\PickerProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Picker\\AbstractPickerProvider.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Picker\\DcaPickerProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Picker\\PagePickerProvider.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Framework\\FrameworkAwareInterface.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Framework\\FrameworkAwareTrait.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Picker\\FilePickerProvider.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\news-bundle\\src\\Picker\\NewsPickerProvider.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\calendar-bundle\\src\\Picker\\EventPickerProvider.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\faq-bundle\\src\\Picker\\FaqPickerProvider.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Picker\\ArticlePickerProvider.php';

$a = ($this->services['knp_menu.factory'] ?? $this->load('getKnpMenu_FactoryService.php'));
$b = ($this->services['router'] ?? $this->getRouterService());

$this->services['contao.picker.builder'] = $instance = new \Contao\CoreBundle\Picker\PickerBuilder($a, $b);

$c = ($this->services['translator'] ?? $this->getTranslatorService());

$d = new \Contao\CoreBundle\Picker\PagePickerProvider($a, $b, $c);

$e = ($this->services['security.token_storage'] ?? ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()));

$d->setTokenStorage($e);
$f = new \Contao\CoreBundle\Picker\FilePickerProvider($a, $b, $c, 'files');

$g = ($this->services['contao.framework'] ?? $this->getContao_FrameworkService());

$f->setFramework($g);
$f->setTokenStorage($e);
$h = new \Contao\NewsBundle\Picker\NewsPickerProvider($a, $b, $c);
$h->setFramework($g);
$h->setTokenStorage($e);
$i = new \Contao\CalendarBundle\Picker\EventPickerProvider($a, $b, $c);
$i->setFramework($g);
$i->setTokenStorage($e);
$j = new \Contao\FaqBundle\Picker\FaqPickerProvider($a, $b, $c);
$j->setFramework($g);
$j->setTokenStorage($e);
$k = new \Contao\CoreBundle\Picker\ArticlePickerProvider($a, $b, $c);
$k->setTokenStorage($e);

$instance->addProvider($d);
$instance->addProvider($f);
$instance->addProvider($h);
$instance->addProvider($i);
$instance->addProvider($j);
$instance->addProvider($k);

return $instance;
