<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.slug' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Slug\\Slug.php';
include_once $this->targetDirs[3].'\\vendor\\ausi\\slug-generator\\src\\SlugGeneratorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\ausi\\slug-generator\\src\\SlugGenerator.php';

return $this->services['contao.slug'] = new \Contao\CoreBundle\Slug\Slug(($this->services['contao.slug.generator'] ?? ($this->services['contao.slug.generator'] = new \Ausi\SlugGenerator\SlugGenerator(['validChars' => '0-9a-z']))), ($this->services['contao.framework'] ?? $this->getContao_FrameworkService()));
