<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.slug.generator' shared service.

include_once $this->targetDirs[3].'\\vendor\\ausi\\slug-generator\\src\\SlugGeneratorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\ausi\\slug-generator\\src\\SlugGenerator.php';

return $this->services['contao.slug.generator'] = new \Ausi\SlugGenerator\SlugGenerator(['validChars' => '0-9a-z']);
