<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.image.image_sizes' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Image\\ImageSizes.php';

return $this->services['contao.image.image_sizes'] = new \Contao\CoreBundle\Image\ImageSizes(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['contao.framework'] ?? $this->getContao_FrameworkService()));
