<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.resource_finder' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Config\\ResourceFinderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Config\\ResourceFinder.php';

return $this->services['contao.resource_finder'] = new \Contao\CoreBundle\Config\ResourceFinder($this->getParameter('contao.resources_paths'));
