<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.slug.valid_characters' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Slug\\ValidCharacters.php';

return $this->services['contao.slug.valid_characters'] = new \Contao\CoreBundle\Slug\ValidCharacters(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['translator'] ?? $this->getTranslatorService()));
