<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.security.authentication_provider.contao_frontend.two_factor_decorator' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\security\\Core\\Authentication\\AuthenticationManagerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security\\Core\\Authentication\\Provider\\AuthenticationProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle\\Security\\Authentication\\Provider\\AuthenticationProviderDecorator.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security\\Core\\Authentication\\Provider\\UserAuthenticationProvider.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security\\Core\\Authentication\\Provider\\DaoAuthenticationProvider.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Security\\Authentication\\Provider\\AuthenticationProvider.php';
include_once $this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\AuthenticationContextFactoryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\AuthenticationContextFactory.php';

return $this->privates['contao.security.authentication_provider.contao_frontend.two_factor_decorator'] = new \Scheb\TwoFactorBundle\Security\Authentication\Provider\AuthenticationProviderDecorator(new \Contao\CoreBundle\Security\Authentication\Provider\AuthenticationProvider(($this->privates['contao.security.frontend_user_provider'] ?? $this->load('getContao_Security_FrontendUserProviderService.php')), ($this->privates['contao.security.user_checker'] ?? $this->load('getContao_Security_UserCheckerService.php')), 'contao_frontend', ($this->privates['security.encoder_factory.generic'] ?? $this->load('getSecurity_EncoderFactory_GenericService.php')), ($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ['lock_period' => 300, 'login_attempts' => 3]), ($this->privates['scheb_two_factor.authenticated_token_handler'] ?? $this->load('getSchebTwoFactor_AuthenticatedTokenHandlerService.php')), ($this->privates['scheb_two_factor.authentication_context_factory'] ?? ($this->privates['scheb_two_factor.authentication_context_factory'] = new \Scheb\TwoFactorBundle\Security\TwoFactor\AuthenticationContextFactory('Scheb\\TwoFactorBundle\\Security\\TwoFactor\\AuthenticationContext'))), ($this->services['security.firewall.map'] ?? $this->getSecurity_Firewall_MapService()), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
