<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.listener.doctrine_schema' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\EventListener\\DoctrineSchemaListener.php';

return $this->privates['contao.listener.doctrine_schema'] = new \Contao\CoreBundle\EventListener\DoctrineSchemaListener(($this->privates['contao.doctrine.schema_provider'] ?? $this->load('getContao_Doctrine_SchemaProviderService.php')));
