<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.opt-in' shared service.

include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\OptIn\\OptInInterface.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\OptIn\\OptIn.php';

return $this->services['contao.opt-in'] = new \Contao\CoreBundle\OptIn\OptIn(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()));
