<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.contao.command.install-web-dir' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\console\\Command\\Command.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\manager-bundle\\src\\Command\\InstallWebDirCommand.php';

return $this->services['console.command.public_alias.contao.command.install-web-dir'] = new \Contao\ManagerBundle\Command\InstallWebDirCommand($this->targetDirs[3]);
