<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.menu.backend_menu_renderer' shared service.

include_once $this->targetDirs[3].'\\vendor\\knplabs\\knp-menu\\src\\Knp\\Menu\\Renderer\\RendererInterface.php';
include_once $this->targetDirs[3].'\\vendor\\contao\\core-bundle\\src\\Menu\\BackendMenuRenderer.php';

return $this->services['contao.menu.backend_menu_renderer'] = new \Contao\CoreBundle\Menu\BackendMenuRenderer(($this->services['twig'] ?? $this->load('getTwigService.php')));
