<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.two_factor.contao_backend' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\security\\Core\\Authentication\\AuthenticationManagerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security\\Core\\Authentication\\Provider\\AuthenticationProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle\\Security\\Authentication\\Provider\\TwoFactorAuthenticationProvider.php';
include_once $this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\Backup\\BackupCodeManagerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\Backup\\NullBackupCodeManager.php';

return $this->privates['security.authentication.provider.two_factor.contao_backend'] = new \Scheb\TwoFactorBundle\Security\Authentication\Provider\TwoFactorAuthenticationProvider('contao_backend', ['auth_form_path' => 'contao_backend_login', 'check_path' => 'contao_backend_two_factor', 'auth_code_parameter_name' => 'verify', 'always_use_default_target_path' => false, 'default_target_path' => '/', 'success_handler' => NULL, 'failure_handler' => NULL, 'authentication_required_handler' => NULL, 'trusted_parameter_name' => '_trusted', 'multi_factor' => false, 'csrf_token_generator' => NULL, 'csrf_parameter' => '_csrf_token', 'csrf_token_id' => 'two_factor', 'provider' => NULL], ($this->privates['scheb_two_factor.provider_registry'] ?? $this->load('getSchebTwoFactor_ProviderRegistryService.php')), new \Scheb\TwoFactorBundle\Security\TwoFactor\Backup\NullBackupCodeManager());
