<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'terminal42.header_replay.header_replay_stop_propagation_listener' shared service.

include_once $this->targetDirs[3].'\\vendor\\terminal42\\header-replay-bundle\\src\\EventListener\\HeaderReplayStopPropagationListener.php';

return $this->privates['terminal42.header_replay.header_replay_stop_propagation_listener'] = new \Terminal42\HeaderReplay\EventListener\HeaderReplayStopPropagationListener(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
